version: '3.8'

services:
  mongodb:
    container_name: mongo
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - ./mongo_residentes:/data/db
            
volumes:
  mongo_residentes: